### POST prodotto
POST http://localhost:8080/api/prodotti
Content-Type: application/json

{
  "nome": "pesce",
  "descrizione": "allevato a terra",
  "CategoriaId": "{{categoria_id}}"
}
> {% client.global.set("prodotto_id", response.body.id) %}
