### Associa user a un magazzino
POST http://localhost:8080/user/586aec34-2a85-4a53-a683-596fd842e79e/magazzino
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "421bb96d-2696-45b0-98e0-8f903c37ea46"
}