### Associa user a un magazzino
POST http://localhost:8080/user/a3050aac-76dc-4181-944d-f2a0c3ddac78/magazzino
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "779a9043-b84b-4208-882f-101a16755701"
}