### togli user a un magazzino
DELETE http://localhost:8080/user/586aec34-2a85-4a53-a683-596fd842e79e/magazzino
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": "5913210f-a25f-4f32-b1d5-782f0d352595"
}