### POST categoria
POST http://localhost:8080/api/categorie
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "surgelati",
  "descrizione": "cibi freddi"
}

> {% client.global.set("categoria_id", response.body.id) %}
