### POST beneficiario
POST http://localhost:8080/api/beneficiari
Content-Type: application/json

{
  "nome": "Mario",
  "cognome": "Rossi",
  "dataNascita": "1990-05-12",
  "magazzinoId": "{{magazzino_id}}"
}
> {% client.global.set("beneficiario_id", response.body.id) %}
