### POST beneficiario
POST http://localhost:8080/api/beneficiari
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Mario",
  "cognome": "Rossi",
  "dataNascita": "1990-05-12",
  "magazzinoId": "edf7cdd0-4d2f-435d-9df8-ef034563eb2f"
}
> {% client.global.set("beneficiario_id", response.body.id) %}
