### PUT beneficiario
PUT  http://localhost:8080/api/beneficiari/{{beneficiario_id}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Luigi",
  "cognome": "Verdi",
  "dataNascita": "1995-07-11",
  "magazzinoId": "edf7cdd0-4d2f-435d-9df8-ef034563eb2f"
}

