### POST prodotto
POST http://localhost:8080/api/magazzino/421bb96d-2696-45b0-98e0-8f903c37ea46/giacenze
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "prodottoId": "{{prodotto_id}}",
  "quantita": 4
}

