### POST prodotto
POST http://localhost:8080/api/magazzino
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Caldonazzo"
}
> {% client.global.set("magazzino_id", response.body.id) %}
