### Delete prodotto
DELETE http://localhost:8080/api/magazzino/5913210f-a25f-4f32-b1d5-782f0d352595/giacenze
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "prodottoId": "{{prodotto_id}}",
  "quantita": 6
}

